[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
NEXT_TELEMETRY_DISABLED = '1'